#!/usr/bin/env php
<?php

if (file_exists('vendor/php-file-iterator/File/Iterator/Autoload.php')) {
    require_once 'vendor/php-file-iterator/File/Iterator/Autoload.php';
}

require_once 'src/Wally/Compile.php';

use Wally\Compile;

$compiler = new Compile();
$compiler->compile();